#!/usr/bin/env bash
set -eu

export ASPNETCORE_ENVIRONMENT=Development

output_base="${1:-test-results}"

run_tests()
{
  tests="$1"
  output_dir="$2"
  base_dir=$(pwd)
  tests_dir="$base_dir/$tests"
  dotnet test "$tests_dir" -xml "$output_dir/$tests"-results.xml
}

run_tests APIEndpointTest "$output_base"
run_tests UnitTest "$output_base"
